site_name: SRE-Docs
site_description: Documentació i desplegament de servidors
site_author: Equip ASIX

theme:
  name: material
  language: ca

nav:
  - Inici: index.md
  - Configuració: servidors.md
  - Gestió de rols: usuaris.md
  - Seguretat: seguretat.md