site_name: SRE-Docs
site_description: Documentació i desplegament de servidors
site_author: Equip ASIX
site_url: https://rendechen14.github.io/Proyecto-Final/

theme:
  name: material
  language: ca

nav:
  - Inici: index.md
  - Configuració: servidors.md
  - Gestió de rols: usuaris.md
  - Seguretat: seguretat.md